/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.RccProduto;
import bean.RccVendaProduto;
import dao.Produto_DAO;
import dao.Venda_produto_DAO;
import java.util.List;
import tools.Util;


/**
 *
 * @author art16
 */
public class JDlgVendaProduto extends javax.swing.JDialog {
    
        private JDlgVenda jDlgVenda;
        private Produto_DAO produto_DAO;
        private Venda_produto_DAO venda_produto_DAO;


    /**
     * Creates new form JDlgVendaProduto
     */
    public JDlgVendaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(550, 230);
        setLocationRelativeTo(null);
        //setTitle("Inclusão de Produtos");
        jTxtValor_total.setEnabled(false);
        jTxtValor_uni.setEnabled(false);
        
        
        produto_DAO = new Produto_DAO();
        venda_produto_DAO = new Venda_produto_DAO();
        
        List listProduto = produto_DAO.listALL();
        for (int i = 0; i < listProduto.size(); i++ ) {
            jCboFk_produto.addItem((RccProduto) listProduto.get(i));
        }
//        
//        if (jDlgVenda.incluindo == true) {
//            setTitle("Inclusão de Produto");
//        }else {
//            setTitle("Alteração de Produto");
//        }
    }
    
    public void setTelaAnterior(JDlgVenda jDlgVenda){//método para se conectar com a tela de Venda 
        this.jDlgVenda = jDlgVenda; //agora ela sabe que ela é ela msm e a outra é a outra
    }
    
    public RccVendaProduto viewBean() { //método para pegar da tela e jogar no bean
        RccVendaProduto rccVendaProduto = new RccVendaProduto(); //criando o bean
        
        int quant = Util.strInt(jTxtQuantidade.getText());  
        
        RccProduto produto1 = (RccProduto) jCboFk_produto.getSelectedItem(); //pega o item selecionado
        rccVendaProduto.setRccFkProduto(produto1.getRccIdProduto());//e grava só a chave no BD
        rccVendaProduto.setRccQuantidade(quant);
        rccVendaProduto.setRccValorUni(Util.strDouble(jTxtValor_uni.getText()));
        
        return rccVendaProduto;
    };
    
    public void beanView(RccVendaProduto rccVendaProduto) { //do banco para a tela
        
        int id_produto = rccVendaProduto.getRccFkProduto(); //trazer do BD o ID da PK
        produto_DAO = new Produto_DAO();//usamos o DAO para acessar o list e então selecionar o ID
        jCboFk_produto.setSelectedItem(produto_DAO.list(id_produto));  //passei o ID para o list e ele retorna um bean para a Cbo
       
        String num = Util.intStr(rccVendaProduto.getRccQuantidade()); //converte int para string (pelo Text)
        jTxtQuantidade.setText(num);

        jTxtValor_uni.setText(Util.doubleStr(rccVendaProduto.getRccValorUni()));

    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCboFk_produto = new javax.swing.JComboBox<RccProduto>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtQuantidade = new javax.swing.JTextField();
        jTxtValor_uni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jBtnOk = new javax.swing.JButton();
        jTxtValor_total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCboFk_produto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboFk_produtoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Produto");

        jLabel2.setText("Quantidade");

        jTxtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeKeyReleased(evt);
            }
        });

        jLabel3.setText("Valor Uni.");

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_certo/recarregar fino (1).png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_certo/confirmar-removebg-preview.png"))); // NOI18N
        jBtnOk.setText("Ok");
        jBtnOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboFk_produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtValor_uni, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTxtValor_total, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboFk_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtValor_uni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtValor_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jBtnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        // TODO add your handling code here:
        
        RccVendaProduto rccVendaProduto = new RccVendaProduto();
        
        RccProduto rccProduto1 = (RccProduto) jCboFk_produto.getSelectedItem();//pega o item selecionado
        rccVendaProduto.setRccFkProduto(rccProduto1.getRccIdProduto());//e grava só a chave no BD
        rccVendaProduto.setRccQuantidade(Util.strInt(jTxtQuantidade.getText() ));
        rccVendaProduto.setRccValorUni(Util.strDouble(jTxtValor_uni.getText()));
        
        //diferenciando inclusão de alteração
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
           jDlgVenda.vendaProdutoController.addBean(rccVendaProduto);
        } else {            
            jDlgVenda.vendaProdutoController.updateBean(jDlgVenda.getSelectedRowProd(), rccVendaProduto);
        }
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.mensagem("Ação cancelada.");
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jCboFk_produtoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboFk_produtoItemStateChanged
        // TODO add your handling code here:
        jTxtQuantidade.setText( "1" );
        RccProduto rccProduto = (RccProduto) jCboFk_produto.getSelectedItem(); //pegar o bean do  item selecionado no combo
        jTxtValor_uni.setText( Util.doubleStr( rccProduto.getRccPreco() )); //pegar o preço unitario
        jTxtValor_total.setText(jTxtValor_uni.getText());
    }//GEN-LAST:event_jCboFk_produtoItemStateChanged

    private void jTxtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKeyReleased
        // TODO add your handling code here:
        if (jTxtQuantidade.getText().isEmpty() == false) {
            double valor_uni = Util.strDouble(jTxtValor_uni.getText());
            double quant = Util.strDouble(jTxtQuantidade.getText());
            jTxtValor_total.setText(String.valueOf(quant * valor_uni));
        } else {
            jTxtValor_total.setText("0");
        }
    }//GEN-LAST:event_jTxtQuantidadeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendaProduto dialog = new JDlgVendaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JComboBox<RccProduto> jCboFk_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtQuantidade;
    private javax.swing.JTextField jTxtValor_total;
    private javax.swing.JTextField jTxtValor_uni;
    // End of variables declaration//GEN-END:variables
}
