package bean;
// Generated 19/09/2023 11:40:58 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RccCliente generated by hbm2java
 */
@Entity
@Table(name="rcc_cliente"
    ,catalog="db_rebeca_celestino"
)
public class RccCliente  implements java.io.Serializable {


     private int rccIdCliente;
     private String rccNome;
     private String rccApelido;
     private String rccSexo;
     private String rccCpf;
     private String rccRg;
     private Date rccNascimento;
     private String rccEmail;
     private String rccTelefone;
     private String rccCelular;
     private String rccUf;
     private String rccCep;
     private String rccCidade;
     private String rccBairro;
     private String rccEndereco;
     private String rccSenha;
     private String rccConfirmeSenha;

    public RccCliente() {
    }

	
    public RccCliente(String rccNome, String rccApelido, String rccCpf, String rccRg, Date rccNascimento, String rccEmail, String rccCelular, String rccUf, String rccCep, String rccCidade, String rccBairro, String rccEndereco, String rccSenha, String rccConfirmeSenha) {
        this.rccNome = rccNome;
        this.rccApelido = rccApelido;
        this.rccCpf = rccCpf;
        this.rccRg = rccRg;
        this.rccNascimento = rccNascimento;
        this.rccEmail = rccEmail;
        this.rccCelular = rccCelular;
        this.rccUf = rccUf;
        this.rccCep = rccCep;
        this.rccCidade = rccCidade;
        this.rccBairro = rccBairro;
        this.rccEndereco = rccEndereco;
        this.rccSenha = rccSenha;
        this.rccConfirmeSenha = rccConfirmeSenha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rcc_id_cliente", unique=true, nullable=false)
    public int getRccIdCliente() {
        return this.rccIdCliente;
    }
    
    public void setRccIdCliente(int rccIdCliente) {
        this.rccIdCliente = rccIdCliente;
    }

    
    @Column(name="rcc_nome", nullable=false, length=60)
    public String getRccNome() {
        return this.rccNome;
    }
    
    public void setRccNome(String rccNome) {
        this.rccNome = rccNome;
    }

    
    @Column(name="rcc_apelido", nullable=false, length=30)
    public String getRccApelido() {
        return this.rccApelido;
    }
    
    public void setRccApelido(String rccApelido) {
        this.rccApelido = rccApelido;
    }

    
    @Column(name="rcc_sexo", length=10)
    public String getRccSexo() {
        return this.rccSexo;
    }
    
    public void setRccSexo(String rccSexo) {
        this.rccSexo = rccSexo;
    }

    
    @Column(name="rcc_cpf", nullable=false, length=11)
    public String getRccCpf() {
        return this.rccCpf;
    }
    
    public void setRccCpf(String rccCpf) {
        this.rccCpf = rccCpf;
    }

    
    @Column(name="rcc_rg", nullable=false, length=10)
    public String getRccRg() {
        return this.rccRg;
    }
    
    public void setRccRg(String rccRg) {
        this.rccRg = rccRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rcc_nascimento", nullable=false, length=10)
    public Date getRccNascimento() {
        return this.rccNascimento;
    }
    
    public void setRccNascimento(Date rccNascimento) {
        this.rccNascimento = rccNascimento;
    }

    
    @Column(name="rcc_email", nullable=false, length=50)
    public String getRccEmail() {
        return this.rccEmail;
    }
    
    public void setRccEmail(String rccEmail) {
        this.rccEmail = rccEmail;
    }

    
    @Column(name="rcc_telefone", length=20)
    public String getRccTelefone() {
        return this.rccTelefone;
    }
    
    public void setRccTelefone(String rccTelefone) {
        this.rccTelefone = rccTelefone;
    }

    
    @Column(name="rcc_celular", nullable=false, length=11)
    public String getRccCelular() {
        return this.rccCelular;
    }
    
    public void setRccCelular(String rccCelular) {
        this.rccCelular = rccCelular;
    }

    
    @Column(name="rcc_uf", nullable=false, length=2)
    public String getRccUf() {
        return this.rccUf;
    }
    
    public void setRccUf(String rccUf) {
        this.rccUf = rccUf;
    }

    
    @Column(name="rcc_cep", nullable=false, length=8)
    public String getRccCep() {
        return this.rccCep;
    }
    
    public void setRccCep(String rccCep) {
        this.rccCep = rccCep;
    }

    
    @Column(name="rcc_cidade", nullable=false, length=40)
    public String getRccCidade() {
        return this.rccCidade;
    }
    
    public void setRccCidade(String rccCidade) {
        this.rccCidade = rccCidade;
    }

    
    @Column(name="rcc_bairro", nullable=false, length=30)
    public String getRccBairro() {
        return this.rccBairro;
    }
    
    public void setRccBairro(String rccBairro) {
        this.rccBairro = rccBairro;
    }

    
    @Column(name="rcc_endereco", nullable=false, length=50)
    public String getRccEndereco() {
        return this.rccEndereco;
    }
    
    public void setRccEndereco(String rccEndereco) {
        this.rccEndereco = rccEndereco;
    }

    
    @Column(name="rcc_senha", nullable=false, length=20)
    public String getRccSenha() {
        return this.rccSenha;
    }
    
    public void setRccSenha(String rccSenha) {
        this.rccSenha = rccSenha;
    }

    
    @Column(name="rcc_confirme_senha", nullable=false, length=20)
    public String getRccConfirmeSenha() {
        return this.rccConfirmeSenha;
    }
    
    public void setRccConfirmeSenha(String rccConfirmeSenha) {
        this.rccConfirmeSenha = rccConfirmeSenha;
    }
    
     @Override
    public String toString() {
        return getRccNome();
    }
    
    public boolean equals(Object object) { //o equals recebe um object
        if (object instanceof RccCliente) { //esse object é um cliente
            RccCliente rccCliente = (RccCliente) object; //esse Cliente é o mesmo do método beanView
            if (this.getRccIdCliente() == rccCliente.getRccIdCliente()) { //this => jCbo == cliente => que esta sendo passado
                return true;
            }
        }
        return false;
    };


}


