/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RccVenda generated by hbm2java
 */
@Entity
@Table(name="rcc_pedido"
    ,catalog="db_rebeca_celestino"
)

/**
 *
 * @author art16
 */
public class RccPedido implements java.io.Serializable{
    
    private int rccIdPedido;
     private Date rccDataPedido;
     private double rccValorTotal;
     private int rccFkCliente;
     private int rccFkVendedor;
     
     public RccPedido() {
         
     }
     
     public RccPedido(Date rccDataVenda, double rccFrete, double rccValorTotal, String rccDescricaoItens, int rccFkCliente, int rccFkVendedor) {
       this.rccDataPedido = rccDataVenda;
       this.rccValorTotal = rccValorTotal;
       this.rccFkCliente = rccFkCliente;
       this.rccFkVendedor = rccFkVendedor;
    }
     
    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rcc_id_pedido", unique=true, nullable=false)
    public int getRccIdPedido() {
        return this.rccIdPedido;
    }
    
    public void setRccIdPedido(int rccIdPedido) {
        this.rccIdPedido = rccIdPedido;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rcc_data_pedido", nullable=false, length=19)
    public Date getRccDataPedido() {
        return this.rccDataPedido;
    }
    
    public void setRccDataPedido(Date rccDataPedido) {
        this.rccDataPedido = rccDataPedido;
    }
    
    @Column(name="rcc_valor_total", nullable=false, precision=7)
    public double getRccValorTotal() {
        return this.rccValorTotal;
    }
    
    public void setRccValorTotal(double rccValorTotal) {
        this.rccValorTotal = rccValorTotal;
    }

    @Column(name="rcc_fk_cliente", nullable=false)
    public int getRccFkCliente() {
        return this.rccFkCliente;
    }
    
    public void setRccFkCliente(int rccFkCliente) {
        this.rccFkCliente = rccFkCliente;
    }

    
    @Column(name="rcc_fk_vendedor", nullable=false)
    public int getRccFkVendedor() {
        return this.rccFkVendedor;
    }
    
    public void setRccFkVendedor(int rccFkVendedor) {
        this.rccFkVendedor = rccFkVendedor;
    }
}
