package bean;
// Generated 20/12/2023 19:07:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RccUsuario generated by hbm2java
 */
@Entity
@Table(name="rcc_usuario"
    ,catalog="db_rebeca_celestino"
)
public class RccUsuario  implements java.io.Serializable {


     private int rccIdUsuario;
     private String rccNome;
     private String rccApelido;
     private String rccCpf;
     private Date rccNascimento;
     private String rccSenha;
     private int rccNivel;
     private String rccAtivo;

    public RccUsuario() {
    }

    public RccUsuario(String rccNome, String rccApelido, String rccCpf, Date rccNascimento, String rccSenha, int rccNivel, String rccAtivo) {
       this.rccNome = rccNome;
       this.rccApelido = rccApelido;
       this.rccCpf = rccCpf;
       this.rccNascimento = rccNascimento;
       this.rccSenha = rccSenha;
       this.rccNivel = rccNivel;
       this.rccAtivo = rccAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rcc_id_usuario", unique=true, nullable=false)
    public int getRccIdUsuario() {
        return this.rccIdUsuario;
    }
    
    public void setRccIdUsuario(int rccIdUsuario) {
        this.rccIdUsuario = rccIdUsuario;
    }

    
    @Column(name="rcc_nome", nullable=false, length=50)
    public String getRccNome() {
        return this.rccNome;
    }
    
    public void setRccNome(String rccNome) {
        this.rccNome = rccNome;
    }

    
    @Column(name="rcc_apelido", nullable=false, length=25)
    public String getRccApelido() {
        return this.rccApelido;
    }
    
    public void setRccApelido(String rccApelido) {
        this.rccApelido = rccApelido;
    }

    
    @Column(name="rcc_cpf", nullable=false, length=11)
    public String getRccCpf() {
        return this.rccCpf;
    }
    
    public void setRccCpf(String rccCpf) {
        this.rccCpf = rccCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rcc_nascimento", nullable=false, length=10)
    public Date getRccNascimento() {
        return this.rccNascimento;
    }
    
    public void setRccNascimento(Date rccNascimento) {
        this.rccNascimento = rccNascimento;
    }

    
    @Column(name="rcc_senha", nullable=false, length=20)
    public String getRccSenha() {
        return this.rccSenha;
    }
    
    public void setRccSenha(String rccSenha) {
        this.rccSenha = rccSenha;
    }

    
    @Column(name="rcc_nivel", nullable=false)
    public int getRccNivel() {
        return this.rccNivel;
    }
    
    public void setRccNivel(int rccNivel) {
        this.rccNivel = rccNivel;
    }

    
    @Column(name="rcc_ativo", nullable=false, length=1)
    public String getRccAtivo() {
        return this.rccAtivo;
    }
    
    public void setRccAtivo(String rccAtivo) {
        this.rccAtivo = rccAtivo;
    }




}


