package bean;
// Generated 20/12/2023 19:07:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RccVenda generated by hbm2java
 */
@Entity
@Table(name="rcc_venda"
    ,catalog="db_rebeca_celestino"
)
public class RccVenda  implements java.io.Serializable {


     private int rccIdVenda;
     private RccCliente rccCliente;
     private RccVendedor rccVendedor;
     private Date rccDataVenda;
     private Double rccFrete;
     private Double rccValorTotal;
     private String rccDescricaoItens;

    public RccVenda() {
    }

	
    public RccVenda(RccCliente rccCliente, RccVendedor rccVendedor, Date rccDataVenda, Double rccFrete, Double rccValorTotal, String rccDescricaoItens) {
        this.rccCliente = rccCliente;
        this.rccVendedor = rccVendedor;
        this.rccDataVenda = rccDataVenda;
        this.rccFrete = rccFrete;
        this.rccValorTotal = rccValorTotal;
        this.rccDescricaoItens = rccDescricaoItens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rcc_id_venda", unique=true, nullable=false)
    public int getRccIdVenda() {
        return this.rccIdVenda;
    }
    
    public void setRccIdVenda(int rccIdVenda) {
        this.rccIdVenda = rccIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rcc_fk_cliente", nullable=false)
    public RccCliente getRccCliente() {
        return this.rccCliente;
    }
    
    public void setRccCliente(RccCliente rccCliente) {
        this.rccCliente = rccCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rcc_fk_vendedor", nullable=false)
    public RccVendedor getRccVendedor() {
        return this.rccVendedor;
    }
    
    public void setRccVendedor(RccVendedor rccVendedor) {
        this.rccVendedor = rccVendedor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rcc_data_venda", nullable=false, length=19)
    public Date getRccDataVenda() {
        return this.rccDataVenda;
    }
    
    public void setRccDataVenda(Date rccDataVenda) {
        this.rccDataVenda = rccDataVenda;
    }

    
    @Column(name="rcc_frete", nullable=false, precision=7)
    public Double getRccFrete() {
        return this.rccFrete;
    }
    
    public void setRccFrete(Double rccFrete) {
        this.rccFrete = rccFrete;
    }

    
    @Column(name="rcc_valor_total", nullable=false, precision=7)
    public Double getRccValorTotal() {
        return this.rccValorTotal;
    }
    
    public void setRccValorTotal(Double rccValorTotal) {
        this.rccValorTotal = rccValorTotal;
    }

    
    @Column(name="rcc_descricao_itens", nullable=false, length=200)
    public String getRccDescricaoItens() {
        return this.rccDescricaoItens;
    }
    
    public void setRccDescricaoItens(String rccDescricaoItens) {
        this.rccDescricaoItens = rccDescricaoItens;
    }


//     @Override
//    public String toString() {
//        return getRccIdVenda();
//    }
    
     @Override
    public boolean equals(Object object) { //o equals recebe um object
        if (object instanceof RccVenda) { //esse object é um venda
            RccVenda rccVenda = (RccVenda) object; //esse venda é o mesmo do método beanView
            if (this.getRccIdVenda() == rccVenda.getRccIdVenda()) { //this => jCbo == venda => que esta sendo passado
                return true;
            }
        }
        return false;
    };
}


