package bean;
// Generated 19/09/2023 11:40:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RccVendedor generated by hbm2java
 */
@Entity
@Table(name="rcc_vendedor"
    ,catalog="db_rebeca_celestino"
)
public class RccVendedor  implements java.io.Serializable {


     private int rccIdVendedor;
     private String rccNome;
     private String rccSexo;
     private String rccCpf;
     private Date rccNascimento;
     private String rccEmail;
     private double rccSalario;

    public RccVendedor() {
    }

    public RccVendedor(String rccNome, String rccSexo, String rccCpf, Date rccNascimento, String rccEmail, double rccSalario) {
       this.rccNome = rccNome;
       this.rccSexo = rccSexo;
       this.rccCpf = rccCpf;
       this.rccNascimento = rccNascimento;
       this.rccEmail = rccEmail;
       this.rccSalario = rccSalario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rcc_id_vendedor", unique=true, nullable=false)
    public int getRccIdVendedor() {
        return this.rccIdVendedor;
    }
    
    public void setRccIdVendedor(int rccIdVendedor) {
        this.rccIdVendedor = rccIdVendedor;
    }

    
    @Column(name="rcc_nome", nullable=false, length=60)
    public String getRccNome() {
        return this.rccNome;
    }
    
    public void setRccNome(String rccNome) {
        this.rccNome = rccNome;
    }

    
    @Column(name="rcc_sexo", length=10)
    public String getRccSexo() {
        return this.rccSexo;
    }
    
    public void setRccSexo(String rccSexo) {
        this.rccSexo = rccSexo;
    }

    
    @Column(name="rcc_cpf", nullable=false, length=11)
    public String getRccCpf() {
        return this.rccCpf;
    }
    
    public void setRccCpf(String rccCpf) {
        this.rccCpf = rccCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rcc_nascimento", nullable=false, length=10)
    public Date getRccNascimento() {
        return this.rccNascimento;
    }
    
    public void setRccNascimento(Date rccNascimento) {
        this.rccNascimento = rccNascimento;
    }

    
    @Column(name="rcc_email", nullable=false, length=50)
    public String getRccEmail() {
        return this.rccEmail;
    }
    
    public void setRccEmail(String rccEmail) {
        this.rccEmail = rccEmail;
    }

    
    @Column(name="rcc_salario", nullable=false, precision=10)
    public double getRccSalario() {
        return this.rccSalario;
    }
    
    public void setRccSalario(double rccSalario) {
        this.rccSalario = rccSalario;
    }
    
     @Override
    public String toString() {
        return getRccNome();
    }
    
    public boolean equals(Object object) { //o equals recebe um object
        if (object instanceof RccVendedor) { //esse object é um Vendedor
            RccVendedor rccVendedor = (RccVendedor) object; //esse Vendedor é o mesmo do método beanView
            if (this.getRccIdVendedor()== rccVendedor.getRccIdVendedor()) { //this => jCbo == vendedor => que esta sendo passado
                return true;
            }
        }
        return false;
    };




}


