package bean;
// Generated 20/12/2023 19:07:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RccVendaProduto generated by hbm2java
 */
@Entity
@Table(name="rcc_venda_produto"
    ,catalog="db_rebeca_celestino"
)
public class RccVendaProduto  implements java.io.Serializable {


     private int rccIdVendaProduto;
     private RccProduto rccProduto;
     private RccVenda rccVenda;
     private int rccQuantidade;
     private Double rccValorUni;

    public RccVendaProduto() {
    }

    public RccVendaProduto(RccProduto rccProduto, RccVenda rccVenda, int rccQuantidade, Double rccValorUni) {
       this.rccProduto = rccProduto;
       this.rccVenda = rccVenda;
       this.rccQuantidade = rccQuantidade;
       this.rccValorUni = rccValorUni;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rcc_id_venda_produto", unique=true, nullable=false)
    public int getRccIdVendaProduto() {
        return this.rccIdVendaProduto;
    }
    
    public void setRccIdVendaProduto(int rccIdVendaProduto) {
        this.rccIdVendaProduto = rccIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="rcc_fk_produto", nullable=false)
    public RccProduto getRccProduto() {
        return this.rccProduto;
    }
    
    public void setRccProduto(RccProduto rccProduto) {
        this.rccProduto = rccProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="rcc_fk_venda", nullable=false)
    public RccVenda getRccVenda() {
        return this.rccVenda;
    }
    
    public void setRccVenda(RccVenda rccVenda) {
        this.rccVenda = rccVenda;
    }

    
    @Column(name="rcc_quantidade", nullable=false)
    public int getRccQuantidade() {
        return this.rccQuantidade;
    }
    
    public void setRccQuantidade(int rccQuantidade) {
        this.rccQuantidade = rccQuantidade;
    }

    
    @Column(name="rcc_valor_uni", nullable=false, precision=7)
    public Double getRccValorUni() {
        return this.rccValorUni;
    }
    
    public void setRccValorUni(Double rccValorUni) {
        this.rccValorUni = rccValorUni;
    }




}


