package bean;
// Generated 19/09/2023 11:40:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RccVendaProduto generated by hbm2java
 */
@Entity
@Table(name="rcc_venda_produto"
    ,catalog="db_rebeca_celestino"
)
public class RccVendaProduto  implements java.io.Serializable {


     private int rccIdVendaProduto;
     private int rccQuantidade;
     private double rccValorUni;
     private int rccFkVenda;
     private int rccFkProduto;

    public RccVendaProduto() {
    }

    public RccVendaProduto(int rccQuantidade, double rccValorUni, int rccFkVenda, int rccFkProduto) {
       this.rccQuantidade = rccQuantidade;
       this.rccValorUni = rccValorUni;
       this.rccFkVenda = rccFkVenda;
       this.rccFkProduto = rccFkProduto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rcc_id_venda_produto", unique=true, nullable=false)
    public int getRccIdVendaProduto() {
        return this.rccIdVendaProduto;
    }
    
    public void setRccIdVendaProduto(int rccIdVendaProduto) {
        this.rccIdVendaProduto = rccIdVendaProduto;
    }

    
    @Column(name="rcc_quantidade", nullable=false)
    public int getRccQuantidade() {
        return this.rccQuantidade;
    }
    
    public void setRccQuantidade(int rccQuantidade) {
        this.rccQuantidade = rccQuantidade;
    }

    
    @Column(name="rcc_valor_uni", nullable=false, precision=7)
    public double getRccValorUni() {
        return this.rccValorUni;
    }
    
    public void setRccValorUni(double rccValorUni) {
        this.rccValorUni = rccValorUni;
    }

    
    @Column(name="rcc_fk_venda", nullable=false)
    public int getRccFkVenda() {
        return this.rccFkVenda;
    }
    
    public void setRccFkVenda(int rccFkVenda) {
        this.rccFkVenda = rccFkVenda;
    }

    
    @Column(name="rcc_fk_produto", nullable=false)
    public int getRccFkProduto() {
        return this.rccFkProduto;
    }
    
    public void setRccFkProduto(int rccFkProduto) {
        this.rccFkProduto = rccFkProduto;
    }




}


